export default {
    firebase: {
        apiKey: 'AIzaSyCPu1cq_G_tzSvrnmKMV02g8yES4j_5kIg',
        authDomain: 'mississauga-dolphins.firebaseapp.com',
        databaseURL: 'https://mississauga-dolphins-staging.firebaseio.com',
        projectId: 'mississauga-dolphins',
        storageBucket: 'mississauga-dolphins.appspot.com',
        messagingSenderId: '562485347443',
    },
    newGame: {
        home: {
            name: '',
            score: 0,
            wickets: 0,
            overs: 0,
            batting: true,
        },
        visitor: {
            name: '',
            score: 0,
            wickets: 0,
            overs: 0,
            batting: false,
        },
        striker: '',
        nonStriker: '',
        bowler: '',
    },
    newGameEvent: {
        title: '',
        division: '',
        cover: {
            source: '',
            thumbnail: '',
        },
        game: true,
        place: {
            name: '',
        },
        match_no: '',
        round_type: '',
    },
    newPlayer: {
        '3FORs': 0,
        '4FORs': 0,
        '5FORs': 0,
        '6FORs': 0,
        '7FORs': 0,
        AVG_RUN: 0,
        BATING_STYLE: '',
        BATTING: {
            '100s': 0,
            '4s': 0,
            '50s': 0,
            '6s': 0,
            AVG: 0,
            HIGHEST: 0,
            INNINGS: 0,
            NO: 0,
            RUNS: 0,
        },
        BOWLING: {
            MDNS: 0,
            OVERS: 0,
            WKTS: 0,
        },
        BOWLING_STYLE: '',
        CTS: 0,
        DATE_JOINED: '',
        DOB: '',
        DP: '',
        ECON: 0,
        FIRST_NAME: '',
        FIRST_PLAYED: '',
        GENERAL: {
            MTCHS: 0,
        },
        GIVEN: '',
        HONOR: '',
        LAST_NAME: '',
        LAST_PLAYED: '',
        ROLE: '',
        SR_OVER: 0,
        ST: 0,
        WK_CTS: 0,
        id: null,
        avatar: {
            source: '',
            thumbnail: '',
        },
    },
    newSponsor: {
        ID: null,
        IMAGE: '',
        NAME: '',
        TAG_LINE: '',
        WEBSITE: '',
    },
    login: {
        username: 'azim.ahmed7@gmail.com',
        password: '826474',
    },
};
